import type { Metadata } from "next";
import { Toaster } from "sonner";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { ReviewService } from "@/features/reviews/repositories/review";
import { AppointmentService } from "@/features/appointments/repositories/appointmet";
import QueryProviders from "@/providers/QueryProvider";
import AdminLayoutClient from "./admin-layout-client";

export const metadata: Metadata = {
  title: "Monksland Motors",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const service = new ReviewService();
  const serviceAppointment = new AppointmentService();

  await Promise.all([
    queryClient.prefetchQuery({
      queryKey: ["reviews"],
      queryFn: () => service.getRecentReviews(),
    }),
    queryClient.prefetchQuery({
      queryKey: ["appointment"],
      queryFn: () => serviceAppointment.getAllRecentAppointments(),
    }),
  ]);

  return (
    <QueryProviders>
      <HydrationBoundary state={dehydrate(queryClient)}>
        <AdminLayoutClient>{children}</AdminLayoutClient>
        <Toaster />
      </HydrationBoundary>
    </QueryProviders>
  );
}
